// Pulls the two things the site must mirror from the rumor app straight out of
// the app's own sources, so the website can never drift from what shipped:
//   1. the version    <- rumor/Cargo.toml      -> src/generated/version.ts
//   2. the agent docs <- rumor/docs/AGENTS_GUIDE.md -> src/generated/agents-guide.md
//
// Runs as a `pre` step before `astro dev` / `astro build` (see package.json), so
// the generated files are always fresh. They live in src/generated/ and are
// gitignored — edit the rumor/ sources, never the copies.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const webDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(webDir, "..");
const genDir = resolve(webDir, "src/generated");

const cargoToml = readFileSync(resolve(repoRoot, "rumor/Cargo.toml"), "utf8");
// First `version = "x.y.z"` under [package] — Cargo.toml puts it on line 3.
const match = cargoToml.match(/^\s*version\s*=\s*"([^"]+)"/m);
if (!match) {
  throw new Error("sync-version: could not find version in rumor/Cargo.toml");
}
const version = match[1];

const guide = readFileSync(resolve(repoRoot, "rumor/docs/AGENTS_GUIDE.md"), "utf8");

mkdirSync(genDir, { recursive: true });
writeFileSync(
  resolve(genDir, "version.ts"),
  `// AUTO-GENERATED by scripts/sync-version.mjs from rumor/Cargo.toml. Do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`,
);
writeFileSync(resolve(genDir, "agents-guide.md"), guide);

console.log(`sync-version: VERSION=${version}, copied AGENTS_GUIDE.md (${guide.length} bytes)`);
